config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'scenarios#index'

  # get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  resources :scenarios do
    resources :levels do
      resources :challenges
    end
  end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :challenge

  validates_presence_of :solution_type
  validates_presence_of :solution
  validates_presence_of :penalty

  def type_enum
    ["Text", "File"]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :challenges

  validates_presence_of :name
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :level
  belongs_to :category
  has_many :hints
  has_one  :answer

  validates_presence_of :name
  validates_presence_of :number
  validates_presence_of :description
  validates_presence_of :points
  validates_presence_of :level
end

app/models/hint.rb
class Hint < ActiveRecord::Base
  belongs_to :challenge

  validates_presence_of :message
  validates_presence_of :points
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :scenario
  has_many :challenges

  validates_presence_of :description
  validates_presence_of :number
  validates_presence_of :scenario
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  has_many :levels
  validates_presence_of :name
  validates_presence_of :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def show
    @challenge = Challenge.find_by_id(params['id'])
  end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController

  def index
    @lvls = Level.all()
  end

  def show
    @lvls = Level.all()
  end

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  def index
    @scenarios = Scenario.all
  end

  def show
    @scenario = Scenario.find_by_id(params['id'])
  end

  def new
    @scenario = Scenario.new
  end

  def create
    @scenario = Scenario.create()
    if @scenario.save
      redirect_to @scenario
    else
      render "new"
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/challenges/_show.html.erb
<div id="challenge">
  <div id="challenge" class="card">
    <h3 class="card-heading simple"><%= @challenge.name %></h3>
    <div class="card-body">
      <h3><%= @challenge.description %></h3>
      <h3><%= @challenge.points %></h3>
      <h3><%= @challenge.number %></h3>
    </div>
  </div>
  <% hint_num = 0 %>
  <% @challenge.hints.each do |hint| %>
  <div class="card">
    <h3 class="card-heading simple">Hint <%= hint_num%></h3>
    <div class="card-body">
    <h3><%= hint.points%></h3>
    <h3><%= hint.message %></h3>
    </div>
  </div>
  <% end %>
  <div class="card">
    <h3 class="card-heading simple">Answer</h3>
    <div class="card-body">
    <%= @challenge.answer.solution %>
    </div>
  </div>
</div>

app/views/challenges/show.js.erb
$("#challenge").remove();
$("#challenge-container").append("<%= escape_javascript(render :partial => 'challenges/show') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CtfSupervisor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/levels/index.html.erb
<div id="wrapper">
  <div id="page-content-wrapper">
    <div class="container-fluid xyz">
      <div class="row">
        <div class="col-lg-12">
          <h1>levels#index</h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/levels/show.html.erb
<div id="wrapper">
  <div id="page-content-wrapper">
    <div class="container-fluid xyz">
      <div class="row">
        <div class="col-lg-12">
          <h1>levels#show</h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/edit.html.erb
<div id="wrapper">
  <div id="page-content-wrapper">
    <div class="container-fluid xyz">
      <div class="row">
        <div class="col-lg-12">
          <h1>scenarios#edit</h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/index.html.erb
<%= render "shared/navbar" %>
<div id="wrapper">
  <div id="page-content-wrapper">
    <div class="container">
      <div class="col-lg-12">
        <div class="row">
          <% 8.times do %>
          <% @scenarios.each do |scenario| %>
          <div class="span4">
            <div class="card">
              <h3 class="card-heading simple"><%= scenario.name %></h3>
              <div class="card-body">
                <%= scenario.description %>
              </div>
              <div class="card-action">
                <%= button_to "Begin", scenario_path(scenario), method: :get, class: "btn btn-block" %>
                <!-- class: "btn btn-primary"-->
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        <div>
      <div>
    <div>
  <div>
<div>

app/views/scenarios/new.html.erb
<div id="wrapper">
  <div id="page-content-wrapper">
    <div class="container-fluid xyz">
      <div class="row">
        <div class="col-lg-12">
          <h1>scenarios#new</h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/show.html.erb
<%= render "shared/navbar" %>
<div id="wrapper">
  <%= render "shared/sidebar" %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-9">
          <div id="challenge-container">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <p class="navbar-text">Progress</p>
  <div class="container">
    <div class="progress-footer">
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
          60%
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <% if not @scenario.nil? %>
  <div class="navbar-header navbar-left">
    <a class="navbar-brand" href="/">Scenario Select</a>
  </div>
  <% end %>
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in?%>
        <li><%= link_to "account", url: '/users/edit' %></li>
        <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %><li>
      <% else %>
        <li><%= button_to "Sign in", new_user_session_path, class: "btn btn-default navbar-btn" %><li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
    <li>
      <span><%= @scenario.name %></span>
    </li>
    <% @scenario.levels.each do |level| %>
    <li class="active">
      <a href="#">
        <span class="fa-stack fa-lg pull-left">
          <i class="fa fa-dashboard fa-stack-1x "></i>
        </span>Level <%= level.number %>
      </a>
      <ul class="nav-pills nav-stacked" style="list-style-type:none;">
      <% level.challenges.each do |challenge| %>
        <li><%= link_to "Challenge #{challenge.number}", scenario_level_challenge_path(@scenario, level, challenge), method: :get, remote: :true %>
      <% end %>
      </ul>
    </li>
    <% end %>
    <li>
      <a href="#">
        <span class="fa-stack fa-lg pull-left">
          <i class="fa fa-server fa-stack-1x "></i>
        </span>Help
      </a>
      <ul class="nav-pills nav-stacked" style="list-style-type:none;">
        <li>
          <a href="#">
            <span class="fa-stack fa-lg pull-left">
              <i class="fa fa-flag fa-stack-1x "></i>
            </span>FAQ
          </a>
        </li>
        <li>
          <a href="#">
            <span class="fa-stack fa-lg pull-left">
              <i class="fa fa-flag fa-stack-1x "></i>
            </span>Chat
          </a>
        </li>
      </ul>
    </li>
  </ul>
</div>